spring:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.MySQLDialect

    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/PULZATOR
        username: root
        password: rooz

app:
    ##jwtSecret: JWTSuperSecretKey
    jwtExpirationInMs : 604800000
## Hibernate Logging
##logging:
##    level:
##    org.hibernate.SQL: DEBUG