spring:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.MySQLDialect

    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/PULZATOR
        username: root
        password: rooz


jwt:
    header: Authorization
    secret: mySecret
    expiration: 604800
    route:
        authentication:
            path: auth
            refresh: refresh

## Hibernate Logging
##logging:
##    level:
##    org.hibernate.SQL: DEBUG